# Generated by Django 6.0.5 on 2026-06-30 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('solicitante_nome', models.CharField(blank=True, max_length=255)),
                ('solicitante_email', models.EmailField(blank=True, max_length=254)),
                ('departamento', models.CharField(blank=True, max_length=255)),
                ('categoria', models.CharField(blank=True, max_length=120)),
                ('subcategoria', models.CharField(blank=True, max_length=120)),
                ('prioridade', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(blank=True, max_length=60)),
                ('origem', models.CharField(blank=True, max_length=120)),
                ('aberto_em_referencia', models.CharField(blank=True, max_length=60)),
                ('ultima_atualizacao_referencia', models.CharField(blank=True, max_length=60)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='AtendimentoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iniciado_em', models.DateTimeField()),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('duracao', models.DurationField(blank=True, null=True)),
                ('tipo_encerramento', models.CharField(blank=True, choices=[('pause', 'Pause'), ('stop', 'Stop')], max_length=10)),
                ('descricao_atividade', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atendente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_atendimentos', to=settings.AUTH_USER_MODEL)),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendimentos', to='core.chamado')),
            ],
            options={
                'ordering': ['-iniciado_em'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('finalizado_em__isnull', True)), fields=('atendente',), name='unique_active_attendance_per_user')],
            },
        ),
    ]
