# Generated by Django 6.0.5 on 2026-07-01 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_chamadoanexo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='atendente_atual',
            field=models.ForeignKey(blank=True, help_text='Atendente que realizou a ultima acao no chamado. Nao representa dono do chamado.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_em_atendimento', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ChamadoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('criacao', 'Criacao'), ('mudanca_status', 'Mudanca de status'), ('atendente_alterado', 'Atendente alterado'), ('comentario', 'Comentario')], max_length=30)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='core.chamado')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_chamado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['criado_em', 'id'],
            },
        ),
    ]
