# Generated by Django 6.0.5 on 2026-07-02 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_chamadomensagem_chamadomensagemanexo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendenciaTI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('convertido_em_chamado', models.BooleanField(default=False)),
                ('convertido_em', models.DateTimeField(blank=True, null=True)),
                ('chamado_gerado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pendencias_origem', to='core.chamado')),
                ('convertido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pendencias_convertidas', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pendencias_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['criado_em', 'id'],
            },
        ),
    ]
