# Generated by Django 6.0.5 on 2026-07-02 17:47

import core.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pendenciati'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrcamentoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('loja', models.CharField(blank=True, max_length=255)),
                ('moeda', models.CharField(choices=[('BRL', 'Real (BRL)'), ('USD', 'Dolar (USD)')], default='BRL', max_length=3)),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('frete', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('desconto', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('link', models.URLField(blank=True, max_length=1000)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('foto_produto', models.ImageField(blank=True, null=True, upload_to=core.models.orcamento_foto_path)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['criado_em', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrcamentoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=core.models.orcamento_doc_path)),
                ('nome_original', models.CharField(blank=True, max_length=255)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='core.orcamentocontrato')),
            ],
            options={
                'ordering': ['enviado_em', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RequisicaoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('fisica', 'Fisica'), ('digital', 'Digital')], default='fisica', max_length=10)),
                ('texto', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_cotacao', 'Em cotacao'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='aberta', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes_contrato', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.AddField(
            model_name='orcamentocontrato',
            name='requisicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos', to='core.requisicaocontrato'),
        ),
        migrations.CreateModel(
            name='SuborcamentoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('loja', models.CharField(blank=True, max_length=255)),
                ('moeda', models.CharField(choices=[('BRL', 'Real (BRL)'), ('USD', 'Dolar (USD)')], default='BRL', max_length=3)),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('frete', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('desconto', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('link', models.URLField(blank=True, max_length=1000)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('foto_produto', models.ImageField(blank=True, null=True, upload_to=core.models.suborcamento_foto_path)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL)),
                ('orcamento_pai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suborcamentos', to='core.orcamentocontrato')),
            ],
            options={
                'ordering': ['criado_em', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SuborcamentoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=core.models.suborcamento_doc_path)),
                ('nome_original', models.CharField(blank=True, max_length=255)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('suborcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='core.suborcamentocontrato')),
            ],
            options={
                'ordering': ['enviado_em', 'id'],
            },
        ),
    ]
