# Generated by Django 6.0.5 on 2026-07-02 20:13

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_documentoti_documentotianexo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssinaturaResponsavelTI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_responsavel', models.CharField(max_length=255)),
                ('imagem_assinatura', models.ImageField(blank=True, null=True, upload_to=core.models.assinatura_upload_path)),
                ('senha_hash', models.CharField(max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assinaturas_ti_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nome_responsavel', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EmprestimoTI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colaborador_nome', models.CharField(max_length=255)),
                ('empresa', models.CharField(blank=True, max_length=255)),
                ('cpf', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=40)),
                ('data_emprestimo', models.DateField()),
                ('previsao_devolucao', models.DateField(blank=True, null=True)),
                ('prazo_indeterminado', models.BooleanField(default=False)),
                ('observacoes_internas', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando documentacao assinada'), ('assinada_ok', 'Documentacao assinada / OK'), ('em_andamento', 'Em andamento'), ('devolvido', 'Devolvido'), ('cancelado', 'Cancelado')], default='aguardando', max_length=20)),
                ('termo_pdf', models.FileField(blank=True, null=True, upload_to=core.models.termo_pdf_upload_path)),
                ('termo_assinado', models.FileField(blank=True, null=True, upload_to=core.models.termo_assinado_upload_path)),
                ('termo_assinado_ok', models.BooleanField(default=False)),
                ('termo_assinado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('assinatura_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emprestimos', to='core.assinaturaresponsavelti')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emprestimos_criados', to=settings.AUTH_USER_MODEL)),
                ('termo_assinado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emprestimos_termo_anexado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EquipamentoEmprestimoTI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_equipamento', models.CharField(max_length=255)),
                ('marca', models.CharField(blank=True, max_length=255)),
                ('modelo', models.CharField(blank=True, max_length=255)),
                ('numero_serie', models.CharField(blank=True, max_length=255)),
                ('patrimonio_etiqueta', models.CharField(blank=True, max_length=255)),
                ('acessorios_entregues', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('emprestimo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamentos', to='core.emprestimoti')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FotoEquipamentoEmprestimoTI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to=core.models.foto_equipamento_upload_path)),
                ('nome_original', models.CharField(blank=True, max_length=255)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fotos_equipamento_enviadas', to=settings.AUTH_USER_MODEL)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='core.equipamentoemprestimoti')),
            ],
            options={
                'ordering': ['enviado_em', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LogUsoAssinaturaTI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usado_em', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.CharField(blank=True, max_length=255)),
                ('assinatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos', to='core.assinaturaresponsavelti')),
                ('emprestimo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usos_assinatura', to='core.emprestimoti')),
                ('usado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usos_assinatura_ti', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-usado_em', '-id'],
            },
        ),
    ]
