# Generated by Django 6.0.5 on 2026-07-13 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_assinaturaresponsavelti_emprestimoti_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('primeiro_nome', models.CharField(blank=True, max_length=255)),
                ('sobrenome', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(blank=True, max_length=40)),
                ('org_unit_path', models.CharField(blank=True, max_length=255)),
                ('ultimo_acesso', models.CharField(blank=True, max_length=40)),
                ('email_recuperacao', models.CharField(blank=True, max_length=255)),
                ('telefone_recuperacao', models.CharField(blank=True, max_length=40)),
                ('telefone_trabalho', models.CharField(blank=True, max_length=40)),
                ('telefone_residencial', models.CharField(blank=True, max_length=40)),
                ('telefone_celular', models.CharField(blank=True, max_length=40)),
                ('employee_id', models.CharField(blank=True, max_length=64)),
                ('tipo_funcionario', models.CharField(blank=True, max_length=120)),
                ('cargo', models.CharField(blank=True, max_length=255)),
                ('email_gestor', models.CharField(blank=True, max_length=255)),
                ('departamento', models.CharField(blank=True, max_length=255)),
                ('centro_custo', models.CharField(blank=True, max_length=120)),
                ('dois_fatores_inscrito', models.BooleanField(default=False)),
                ('dois_fatores_forcado', models.BooleanField(default=False)),
                ('uso_email', models.CharField(blank=True, max_length=40)),
                ('uso_drive', models.CharField(blank=True, max_length=40)),
                ('uso_fotos', models.CharField(blank=True, max_length=40)),
                ('limite_armazenamento', models.CharField(blank=True, max_length=40)),
                ('armazenamento_usado', models.CharField(blank=True, max_length=40)),
                ('licencas', models.TextField(blank=True)),
                ('gemini_status', models.CharField(blank=True, max_length=120)),
                ('importado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('importado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_email_importadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conta de e-mail',
                'verbose_name_plural': 'Contas de e-mail',
                'ordering': ['primeiro_nome', 'sobrenome', 'email'],
            },
        ),
    ]
