# Generated by Django 6.0.5 on 2026-07-13 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_contaemail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ramal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colaborador', models.CharField(blank=True, max_length=255)),
                ('setor', models.CharField(blank=True, max_length=255)),
                ('telefone', models.CharField(blank=True, max_length=60)),
                ('ramal', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('conta_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ramais', to='core.contaemail')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ramais_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ramal',
                'verbose_name_plural': 'Ramais',
                'ordering': ['colaborador', 'setor', 'id'],
            },
        ),
    ]
