# Generated by Django 6.0.5 on 2026-07-14 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_seed_ramais'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LicencaSoftware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180)),
                ('quantidade_licencas', models.PositiveIntegerField(default=1)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='softwares_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Software',
                'verbose_name_plural': 'Softwares',
                'ordering': ['nome', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Licenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(blank=True, default='', max_length=240)),
                ('email_vinculado', models.EmailField(blank=True, default='', max_length=254)),
                ('tipo_expiracao', models.CharField(choices=[('indeterminado', 'Indeterminado'), ('expira_em', 'Prazo para expirar')], default='indeterminado', max_length=20)),
                ('expira_em', models.DateField(blank=True, null=True)),
                ('forma_pagamento', models.CharField(blank=True, default='', max_length=80)),
                ('final_cartao', models.CharField(blank=True, default='', max_length=4)),
                ('usuario_atribuido', models.CharField(blank=True, default='', max_length=180)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licencas_criadas', to=settings.AUTH_USER_MODEL)),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licencas', to='core.licencasoftware')),
            ],
            options={
                'verbose_name': 'Licenca de software',
                'verbose_name_plural': 'Licencas de software',
                'ordering': ['software__nome', 'usuario_atribuido', 'email_vinculado', 'id'],
            },
        ),
    ]
