# Generated by Django 6.0.5 on 2026-07-14 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_seed_licencas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnderecoIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('servers', 'Servidores'), ('switches', 'Switchs'), ('idface_turnstiles', 'IdFace + Catracas'), ('printers', 'Impressoras'), ('wifi', 'Wi-Fi'), ('monitoring', 'Zabbix & Grafana')], max_length=30)),
                ('endereco_ip', models.CharField(max_length=45, unique=True)),
                ('nome', models.CharField(blank=True, default='', max_length=180)),
                ('fabricante', models.CharField(blank=True, default='', max_length=180)),
                ('mac', models.CharField(blank=True, default='', max_length=80)),
                ('acesso', models.TextField(blank=True, default='')),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ips_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IP',
                'verbose_name_plural': 'IPs',
                'ordering': ['categoria', 'endereco_ip'],
            },
        ),
    ]
