# Generated by Django 6.0.5 on 2026-07-14 13:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_seed_ips'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicoFeito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_servico', models.CharField(max_length=180)),
                ('empresa', models.CharField(blank=True, default='', max_length=180)),
                ('descricao', models.TextField(blank=True, default='')),
                ('data_servico', models.DateField(default=django.utils.timezone.localdate)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicos_feitos_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Servico feito',
                'verbose_name_plural': 'Servicos feitos',
                'ordering': ['-data_servico', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ServicoFeitoAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='servicos_feitos/')),
                ('nome_original', models.CharField(blank=True, default='', max_length=255)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='core.servicofeito')),
            ],
            options={
                'verbose_name': 'Anexo de servico feito',
                'verbose_name_plural': 'Anexos de servicos feitos',
                'ordering': ['id'],
            },
        ),
    ]
