# Generated by Django 6.0.5 on 2026-07-14 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_seed_servicos_feitos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('forma_pagamento', models.CharField(blank=True, default='', max_length=80)),
                ('final_cartao', models.CharField(blank=True, default='', max_length=4)),
                ('periodicidade', models.CharField(choices=[('mensal', 'Mensal'), ('anual', 'Anual'), ('pagamento_unico', 'Pagamento unico')], default='mensal', max_length=20)),
                ('inicio', models.DateField(blank=True, null=True)),
                ('fim', models.DateField(blank=True, null=True)),
                ('encerrado_em', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['nome', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContratoAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='contratos_ti/')),
                ('nome_original', models.CharField(blank=True, default='', max_length=255)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='core.contrato')),
            ],
            options={
                'verbose_name': 'Anexo de contrato',
                'verbose_name_plural': 'Anexos de contratos',
                'ordering': ['id'],
            },
        ),
    ]
