# Generated by Django 6.0.5 on 2026-07-14 18:45

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_seed_contratos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuturaDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.DateField(help_text='Use o primeiro dia do mes de referencia.')),
                ('nota_fiscal', models.CharField(blank=True, default='', max_length=80)),
                ('copias_total', models.PositiveIntegerField(default=0)),
                ('copias_cor', models.PositiveIntegerField(default=0)),
                ('franquia_copias', models.PositiveIntegerField(default=23000)),
                ('franquia_valor', models.DecimalField(decimal_places=2, default=Decimal('1610.00'), max_digits=12)),
                ('valor_copia_excedente', models.DecimalField(decimal_places=4, default=Decimal('0.07'), max_digits=8)),
                ('valor_copia_cor', models.DecimalField(decimal_places=4, default=Decimal('0.75'), max_digits=8)),
                ('copias_excedentes', models.PositiveIntegerField(default=0)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('documento', models.FileField(blank=True, null=True, upload_to='futura_digital/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='futura_digital_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Futura Digital',
                'verbose_name_plural': 'Futura Digital',
                'ordering': ['-mes_referencia', '-id'],
            },
        ),
    ]
