# Generated by Django 6.0.5 on 2026-07-14 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_seed_futura_digital'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('geral', 'Geral'), ('configuracao', 'Configuracao'), ('resolucao', 'Resolucao')], default='geral', max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.TextField(blank=True, default='')),
                ('anexo', models.FileField(blank=True, null=True, upload_to='dicas/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dicas_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dica',
                'verbose_name_plural': 'Dicas',
                'ordering': ['categoria', 'titulo', 'id'],
            },
        ),
    ]
