# Generated by Django 6.0.5 on 2026-07-14 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_seed_dicas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Starlink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160)),
                ('local', models.CharField(blank=True, default='', max_length=180)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('senha', models.CharField(blank=True, default='', max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('forma_pagamento', models.CharField(choices=[('pix', 'Pix'), ('cartao', 'Cartao')], default='cartao', max_length=12)),
                ('final_cartao', models.CharField(blank=True, default='', max_length=4)),
                ('identificador', models.CharField(blank=True, default='', max_length=80)),
                ('versao_software', models.CharField(blank=True, default='', max_length=80)),
                ('numero_serie', models.CharField(blank=True, default='', max_length=120)),
                ('numero_kit', models.CharField(blank=True, default='', max_length=120)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='starlinks_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Starlink',
                'verbose_name_plural': 'Starlinks',
                'ordering': ['nome', 'id'],
            },
        ),
    ]
