# Generated by Django 6.0.5 on 2026-07-14 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_seed_starlinks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='starlink',
            name='senha',
        ),
    ]
