# Generated by Django 6.0.5 on 2026-07-14 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_starlink_senha'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CofreConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senha_mestra_hash', models.CharField(blank=True, default='', max_length=255)),
                ('tentativas_falhas', models.PositiveSmallIntegerField(default=0)),
                ('bloqueado_ate', models.DateTimeField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuracao do Cofre',
                'verbose_name_plural': 'Configuracoes do Cofre',
            },
        ),
        migrations.CreateModel(
            name='CofreCredencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotulo', models.CharField(max_length=160)),
                ('usuario', models.CharField(blank=True, default='', max_length=180)),
                ('senha_cifrada', models.TextField(blank=True, default='')),
                ('notas', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cofre_credenciais_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credencial do Cofre',
                'verbose_name_plural': 'Credenciais do Cofre',
                'ordering': ['rotulo', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CofreAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('acao', models.CharField(choices=[('unlock_ok', 'Destravou o cofre'), ('unlock_falha', 'Falha ao destravar'), ('bloqueio', 'Bloqueio temporario'), ('lock', 'Travou o cofre'), ('senha_mestra', 'Senha-mestra definida/alterada'), ('cred_criada', 'Credencial criada'), ('cred_atualizada', 'Credencial atualizada'), ('cred_excluida', 'Credencial excluida'), ('cred_revelada', 'Senha revelada/copiada')], max_length=32)),
                ('rotulo_credencial', models.CharField(blank=True, default='', max_length=160)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('detalhes', models.CharField(blank=True, default='', max_length=255)),
                ('ator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cofre_auditorias', to=settings.AUTH_USER_MODEL)),
                ('credencial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to='core.cofrecredencial')),
            ],
            options={
                'verbose_name': 'Auditoria do Cofre',
                'verbose_name_plural': 'Auditoria do Cofre',
                'ordering': ['-criado_em', '-id'],
            },
        ),
    ]
