# Generated by Django 6.0.5 on 2026-07-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_seed_cofre'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=False, help_text='Liga/desliga o envio de e-mails de notificacao.')),
                ('host', models.CharField(blank=True, default='smtp.gmail.com', max_length=255)),
                ('porta', models.PositiveIntegerField(default=587)),
                ('usar_tls', models.BooleanField(default=True)),
                ('usar_ssl', models.BooleanField(default=False)),
                ('timeout', models.PositiveIntegerField(default=15, help_text='Tempo limite (segundos) da conexao SMTP.')),
                ('usuario', models.CharField(blank=True, default='', help_text='Conta que autentica no SMTP (ex.: seu-email@gmail.com).', max_length=255)),
                ('senha_cifrada', models.TextField(blank=True, default='')),
                ('remetente', models.CharField(blank=True, default='', help_text='E-mail que aparece como remetente. Em branco usa a conta de envio.', max_length=255)),
                ('remetente_nome', models.CharField(blank=True, default='Chamados TI', max_length=160)),
                ('emails_ti', models.TextField(blank=True, default='', help_text='E-mail(s) da equipe de TI que recebem as notificacoes.')),
                ('notif_novo_chamado', models.BooleanField(default=True)),
                ('notif_nova_mensagem', models.BooleanField(default=True)),
                ('notif_mudanca_status', models.BooleanField(default=True)),
                ('notif_fechamento', models.BooleanField(default=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuracao de E-mail',
                'verbose_name_plural': 'Configuracao de E-mail',
            },
        ),
    ]
