# Generated by Django 6.0.5 on 2026-07-15 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_emailconfig'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='atendimentohistorico',
            name='unique_active_attendance_per_user',
        ),
    ]
