# Generated by Django 6.0.5 on 2026-07-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_atendimentohistorico_unique_active_attendance_per_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicaocontrato',
            name='status',
            field=models.CharField(choices=[('aberta', 'Aberta'), ('em_cotacao', 'Esperando aprovacao'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='aberta', max_length=20),
        ),
    ]
