# Generated by Django 6.0.5 on 2026-07-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_requisicaocontrato_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='retiradainsumoti',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saida')], default='saida', max_length=10),
        ),
        migrations.AlterField(
            model_name='retiradainsumoti',
            name='entregue_para',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='retiradainsumoti',
            name='motivo',
            field=models.TextField(blank=True),
        ),
    ]
