# Generated by Django 6.0.5 on 2026-07-17 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_pendenciati_prioridade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pendenciati',
            options={'ordering': ['prioridade', '-criado_em', '-id']},
        ),
    ]
