# Generated by Django 6.0.5 on 2026-07-17 13:55

from django.db import migrations, models


def limpar_prioridades(apps, schema_editor):
    """Zera a cor das pendencias existentes: elas tinham o antigo default 3
    (que pintava todas). O padrao agora e "sem cor" (nulo)."""
    PendenciaTI = apps.get_model('core', 'PendenciaTI')
    PendenciaTI.objects.update(prioridade=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_pendenciati_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pendenciati',
            options={'ordering': [models.OrderBy(models.F('prioridade'), nulls_last=True), '-criado_em', '-id']},
        ),
        migrations.AlterField(
            model_name='pendenciati',
            name='prioridade',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Urgente'), (2, 'Alta'), (3, 'Media'), (4, 'Baixa'), (5, 'Minima')], default=None, help_text='1 = mais urgente (vermelho), 5 = menos urgente (verde); vazio = sem cor.', null=True),
        ),
        migrations.RunPython(limpar_prioridades, migrations.RunPython.noop),
    ]
