# Generated by Django 6.0.5 on 2026-07-23 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_equipamento_datas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicaocontratoevento',
            name='tipo',
            field=models.CharField(choices=[('criacao', 'Criacao'), ('aprovacao', 'Aprovacao de orcamento'), ('entrega', 'Entrega'), ('status', 'Mudanca de status'), ('edicao', 'Edicao')], max_length=20),
        ),
    ]
