# Generated by Django 6.0.5 on 2026-07-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_normaliza_em_atendimento_sem_play'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamadoevento',
            name='tipo',
            field=models.CharField(choices=[('criacao', 'Criacao'), ('mudanca_status', 'Mudanca de status'), ('atendente_alterado', 'Atendente alterado'), ('comentario', 'Comentario'), ('encerramento_direto', 'Encerramento sem atendimento ativo')], max_length=30),
        ),
    ]
