# Generated by Django 6.0.5 on 2026-07-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_evento_encerramento_direto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicaocontrato',
            name='status',
            field=models.CharField(choices=[('aberta', 'Aberta'), ('em_cotacao', 'Esperando aprovacao'), ('aguardando_entrega', 'Aguardando entrega'), ('entregue', 'Entregue'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada'), ('nao_aprovada', 'Nao aprovada')], default='aberta', max_length=20),
        ),
    ]
