# Generated by Django 6.0.5 on 2026-07-27 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_requisicao_status_nao_aprovada'),
    ]

    operations = [
        migrations.CreateModel(
            name='KasperskyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licencas_contratadas', models.PositiveIntegerField(default=100)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kaspersky - configuracao',
                'verbose_name_plural': 'Kaspersky - configuracao',
            },
        ),
        migrations.CreateModel(
            name='KasperskyDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('setor', models.CharField(blank=True, default='', max_length=120)),
                ('responsavel', models.CharField(blank=True, default='', max_length=120)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('status', models.CharField(blank=True, default='', max_length=40)),
                ('agente_executando', models.BooleanField(default=False)),
                ('versao_agente', models.CharField(blank=True, default='', max_length=40)),
                ('versao_aplicativo', models.CharField(blank=True, default='', max_length=40)),
                ('endereco_ip', models.CharField(blank=True, default='', max_length=45)),
                ('grupo', models.CharField(blank=True, default='', max_length=180)),
                ('ultima_conexao', models.DateTimeField(blank=True, null=True)),
                ('no_ultimo_export', models.BooleanField(default=True)),
                ('importado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ramal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispositivos_kaspersky', to='core.ramal')),
            ],
            options={
                'verbose_name': 'Kaspersky - dispositivo',
                'verbose_name_plural': 'Kaspersky - dispositivos',
                'ordering': ['nome'],
            },
        ),
    ]
