# Generated by Django 6.0.5 on 2026-07-27 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_kaspersky'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('usuario_glpi', models.CharField(blank=True, default='', max_length=180)),
                ('localizacao', models.CharField(blank=True, default='', max_length=180)),
                ('status', models.CharField(blank=True, default='', max_length=60)),
                ('fabricante', models.CharField(blank=True, default='', max_length=120)),
                ('tipo', models.CharField(blank=True, default='', max_length=60)),
                ('modelo', models.CharField(blank=True, default='', max_length=180)),
                ('processador', models.CharField(blank=True, default='', max_length=180)),
                ('sistema_operacional', models.CharField(blank=True, default='', max_length=180)),
                ('atualizado_glpi', models.DateTimeField(blank=True, null=True)),
                ('no_ultimo_import', models.BooleanField(default=True)),
                ('importado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ramal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='computadores', to='core.ramal')),
            ],
            options={
                'verbose_name': 'Computador (GLPI)',
                'verbose_name_plural': 'Computadores (GLPI)',
                'ordering': ['nome'],
            },
        ),
    ]
