# Generated by Django 6.0.5 on 2026-07-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_remove_contatos_kaspersky'),
    ]

    operations = [
        migrations.AddField(
            model_name='ramal',
            name='kaspersky_instalado',
            field=models.BooleanField(default=False),
        ),
    ]
