# Generated by Django 6.0.5 on 2026-08-18 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_ramal_kaspersky_instalado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMenuConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=40, unique=True)),
                ('rotulo', models.CharField(blank=True, default='', help_text='Rotulo escolhido pelo titular. Em branco usa o rotulo padrao.', max_length=40)),
                ('ordem', models.PositiveIntegerField(blank=True, help_text='Posicao no menu. Nulo usa a ordem padrao do catalogo.', null=True)),
                ('visivel', models.BooleanField(default=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Item do menu',
                'verbose_name_plural': 'Itens do menu',
                'ordering': ['ordem', 'chave'],
            },
        ),
        migrations.CreateModel(
            name='PainelAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('interface', 'Interface'), ('usuarios', 'Usuarios'), ('dados', 'Dados'), ('operacao', 'Operacao')], max_length=20)),
                ('acao', models.CharField(max_length=60)),
                ('alvo', models.CharField(blank=True, default='', max_length=200)),
                ('detalhe', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes_painel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acao do painel',
                'verbose_name_plural': 'Acoes do painel',
                'ordering': ['-criado_em'],
            },
        ),
    ]
