# Generated by Django 6.0.5 on 2026-08-19 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_itemmenuconfig_painelauditoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotulo', models.CharField(help_text='Para que serve / de quem e este token.', max_length=120)),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('somente_leitura', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ultimo_uso', models.DateTimeField(blank=True, null=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tokens_api_criados', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(help_text='Conta cujas permissoes valem para os pedidos com este token.', on_delete=django.db.models.deletion.CASCADE, related_name='tokens_api', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token de API',
                'verbose_name_plural': 'Tokens de API',
                'ordering': ['rotulo'],
            },
        ),
    ]
