# Generated by Django 6.0.5 on 2026-09-03 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_tokenapi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChamadoExclusaoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chamado_numero', models.CharField(max_length=30)),
                ('chamado_titulo', models.CharField(max_length=255)),
                ('motivo', models.TextField()),
                ('excluido_em', models.DateTimeField(auto_now_add=True)),
                ('excluido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exclusoes_de_chamados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exclusao de chamado',
                'verbose_name_plural': 'Exclusoes de chamados',
                'ordering': ['-excluido_em', '-id'],
            },
        ),
    ]
