from django.urls import path

from .views import (
    closed_ticket_detail_view,
    closed_tickets_search_view,
    contrato_orcamento_documento_view,
    contrato_orcamento_foto_view,
    contrato_suborcamento_documento_view,
    contrato_suborcamento_foto_view,
    contratos_dashboard_view,
    assinatura_create_view,
    assinaturas_list_view,
    create_ticket_kanban_view,
    dashboard_redirect_view,
    documento_anexo_download_view,
    documento_create_view,
    documento_detail_view,
    documentos_dashboard_view,
    download_anexo_view,
    emprestimo_anexar_termo_assinado_view,
    emprestimo_baixar_termo_view,
    emprestimo_create_view,
    emprestimo_detail_view,
    emprestimo_marcar_ok_view,
    emprestimos_dashboard_view,
    download_message_anexo_view,
    finish_attendance_view,
    history_search_view,
    history_view,
    insumo_create_view,
    insumos_dashboard_view,
    login_view,
    logout_view,
    move_ticket_view,
    my_tickets_view,
    open_ticket_view,
    orcamento_create_view,
    pendencia_convert_view,
    pendencia_create_view,
    pendencia_detail_view,
    permissions_view,
    retirada_create_view,
    requisicao_create_view,
    requisicao_delete_view,
    requisicao_detail_view,
    start_attendance_view,
    suborcamento_create_view,
    ticket_detail_view,
    ticket_message_create_view,
    tickets_dashboard_view,
    toggle_attendant_permission_view,
)

urlpatterns = [
    path("dashboard/", dashboard_redirect_view, name="dashboard"),
    path("chamados/", tickets_dashboard_view, name="tickets_dashboard"),
    path("chamados/atendimento/iniciar/", start_attendance_view, name="start_attendance"),
    path("chamados/atendimento/encerrar/", finish_attendance_view, name="finish_attendance"),
    path("chamados/mover/", move_ticket_view, name="move_ticket"),
    path("chamados/criar/", create_ticket_kanban_view, name="create_ticket_kanban"),
    path("chamados/fechados/buscar/", closed_tickets_search_view, name="closed_tickets_search"),
    path("chamados/fechados/<str:numero>/", closed_ticket_detail_view, name="closed_ticket_detail"),
    path("chamados/pendencias/criar/", pendencia_create_view, name="pendencia_create"),
    path("chamados/pendencias/<int:pendencia_id>/", pendencia_detail_view, name="pendencia_detail"),
    path("chamados/pendencias/<int:pendencia_id>/converter/", pendencia_convert_view, name="pendencia_convert"),
    path("meus-chamados/", my_tickets_view, name="my_tickets"),
    path("meus-chamados/novo/", open_ticket_view, name="open_ticket"),
    path("meus-chamados/<str:numero>/", ticket_detail_view, name="ticket_detail"),
    path("meus-chamados/<str:numero>/mensagens/", ticket_message_create_view, name="ticket_message_create"),
    path("meus-chamados/<str:numero>/anexo/<int:anexo_id>/", download_anexo_view, name="download_anexo"),
    path("meus-chamados/<str:numero>/mensagens/anexo/<int:anexo_id>/", download_message_anexo_view, name="download_message_anexo"),
    path("contratos/", contratos_dashboard_view, name="contratos_dashboard"),
    path("contratos/requisicoes/criar/", requisicao_create_view, name="requisicao_create"),
    path("contratos/requisicoes/<int:requisicao_id>/", requisicao_detail_view, name="requisicao_detail"),
    path("contratos/requisicoes/<int:requisicao_id>/excluir/", requisicao_delete_view, name="requisicao_delete"),
    path("contratos/requisicoes/<int:requisicao_id>/orcamentos/criar/", orcamento_create_view, name="orcamento_create"),
    path("contratos/orcamentos/<int:orcamento_id>/suborcamentos/criar/", suborcamento_create_view, name="suborcamento_create"),
    path("contratos/orcamentos/<int:orcamento_id>/foto/", contrato_orcamento_foto_view, name="contrato_orcamento_foto"),
    path("contratos/suborcamentos/<int:suborcamento_id>/foto/", contrato_suborcamento_foto_view, name="contrato_suborcamento_foto"),
    path("contratos/documentos/orcamento/<int:documento_id>/", contrato_orcamento_documento_view, name="contrato_orcamento_documento"),
    path("contratos/documentos/suborcamento/<int:documento_id>/", contrato_suborcamento_documento_view, name="contrato_suborcamento_documento"),
    path("emprestimos/", emprestimos_dashboard_view, name="emprestimos_dashboard"),
    path("emprestimos/criar/", emprestimo_create_view, name="emprestimo_create"),
    path("emprestimos/assinaturas/", assinaturas_list_view, name="assinaturas_list"),
    path("emprestimos/assinaturas/criar/", assinatura_create_view, name="assinatura_create"),
    path("emprestimos/<int:emprestimo_id>/", emprestimo_detail_view, name="emprestimo_detail"),
    path("emprestimos/<int:emprestimo_id>/baixar-termo/", emprestimo_baixar_termo_view, name="emprestimo_baixar_termo"),
    path("emprestimos/<int:emprestimo_id>/anexar-termo-assinado/", emprestimo_anexar_termo_assinado_view, name="emprestimo_anexar_termo_assinado"),
    path("emprestimos/<int:emprestimo_id>/marcar-documentacao-ok/", emprestimo_marcar_ok_view, name="emprestimo_marcar_ok"),
    path("documentos/", documentos_dashboard_view, name="documentos_dashboard"),
    path("documentos/criar/", documento_create_view, name="documento_create"),
    path("documentos/<int:documento_id>/", documento_detail_view, name="documento_detail"),
    path("documentos/anexos/<int:anexo_id>/", documento_anexo_download_view, name="documento_anexo_download"),
    path("insumos/", insumos_dashboard_view, name="insumos_dashboard"),
    path("insumos/criar/", insumo_create_view, name="insumo_create"),
    path("insumos/<int:insumo_id>/retirar/", retirada_create_view, name="retirada_create"),
    path("historico/", history_view, name="history"),
    path("historico/buscar/", history_search_view, name="history_search"),
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path("permissoes/", permissions_view, name="permissions"),
    path("permissoes/<int:user_id>/toggle-atendente/", toggle_attendant_permission_view, name="toggle_attendant_permission"),
]
