from django.urls import path

from .views import (
    closed_ticket_detail_view,
    closed_tickets_search_view,
    cofre_credencial_create_view,
    cofre_credencial_delete_view,
    cofre_credencial_reveal_view,
    cofre_credencial_update_view,
    cofre_dashboard_view,
    cofre_lock_view,
    cofre_set_master_view,
    cofre_unlock_view,
    contrato_orcamento_documento_view,
    contrato_orcamento_foto_view,
    contrato_suborcamento_documento_view,
    contrato_suborcamento_foto_view,
    contratos_dashboard_view,
    contratos_ti_dashboard_view,
    dica_anexo_view,
    dica_create_view,
    dica_delete_view,
    dica_update_view,
    dicas_dashboard_view,
    contrato_ti_anexo_delete_view,
    contrato_ti_anexo_download_view,
    contrato_ti_create_view,
    contrato_ti_delete_view,
    contrato_ti_detail_view,
    contrato_ti_update_view,
    assinatura_create_view,
    assinaturas_list_view,
    create_ticket_kanban_view,
    dashboard_redirect_view,
    documento_anexo_download_view,
    documento_create_view,
    documento_detail_view,
    documentos_dashboard_view,
    download_anexo_view,
    email_config_save_view,
    email_config_test_view,
    email_config_view,
    email_detail_view,
    email_import_view,
    emails_dashboard_view,
    futura_digital_create_view,
    futura_digital_dashboard_view,
    futura_digital_delete_view,
    futura_digital_documento_view,
    futura_digital_update_view,
    ramais_dashboard_view,
    ramal_create_view,
    ramal_delete_view,
    ramal_update_view,
    emprestimo_anexar_termo_assinado_view,
    emprestimo_baixar_termo_view,
    emprestimo_create_view,
    emprestimo_detail_view,
    emprestimo_foto_view,
    emprestimo_marcar_ok_view,
    emprestimo_termo_assinado_view,
    emprestimos_dashboard_view,
    download_message_anexo_view,
    finish_attendance_view,
    history_search_view,
    history_view,
    insumo_create_view,
    insumo_delete_view,
    insumo_entrada_view,
    insumo_update_view,
    insumos_dashboard_view,
    notificacoes_stream_view,
    retiradas_search_view,
    ip_create_view,
    ip_delete_view,
    ip_update_view,
    ips_dashboard_view,
    licenca_create_view,
    licenca_delete_view,
    licenca_software_create_view,
    licenca_software_delete_view,
    licenca_software_update_view,
    licenca_update_view,
    licencas_dashboard_view,
    login_view,
    logout_view,
    move_ticket_view,
    my_tickets_view,
    open_ticket_view,
    orcamento_aprovar_view,
    orcamento_create_view,
    pendencia_convert_view,
    pendencia_create_view,
    pendencia_delete_view,
    pendencia_detail_view,
    permissions_view,
    retirada_create_view,
    servico_feito_anexo_delete_view,
    servico_feito_anexo_download_view,
    servico_feito_create_view,
    servico_feito_delete_view,
    servico_feito_detail_view,
    servico_feito_update_view,
    servicos_feitos_dashboard_view,
    requisicao_create_view,
    requisicao_delete_view,
    requisicao_detail_view,
    requisicao_marcar_entregue_view,
    start_attendance_view,
    starlink_create_view,
    starlink_delete_view,
    starlink_update_view,
    starlinks_dashboard_view,
    suborcamento_create_view,
    ticket_detail_view,
    ticket_message_create_view,
    tickets_dashboard_view,
    toggle_attendant_permission_view,
)

urlpatterns = [
    path("dashboard/", dashboard_redirect_view, name="dashboard"),
    path("chamados/", tickets_dashboard_view, name="tickets_dashboard"),
    path("chamados/atendimento/iniciar/", start_attendance_view, name="start_attendance"),
    path("chamados/atendimento/encerrar/", finish_attendance_view, name="finish_attendance"),
    path("chamados/mover/", move_ticket_view, name="move_ticket"),
    path("chamados/criar/", create_ticket_kanban_view, name="create_ticket_kanban"),
    path("chamados/fechados/buscar/", closed_tickets_search_view, name="closed_tickets_search"),
    path("chamados/fechados/<str:numero>/", closed_ticket_detail_view, name="closed_ticket_detail"),
    path("chamados/pendencias/criar/", pendencia_create_view, name="pendencia_create"),
    path("chamados/pendencias/<int:pendencia_id>/", pendencia_detail_view, name="pendencia_detail"),
    path("chamados/pendencias/<int:pendencia_id>/converter/", pendencia_convert_view, name="pendencia_convert"),
    path("chamados/pendencias/<int:pendencia_id>/excluir/", pendencia_delete_view, name="pendencia_delete"),
    path("meus-chamados/", my_tickets_view, name="my_tickets"),
    path("meus-chamados/novo/", open_ticket_view, name="open_ticket"),
    path("meus-chamados/<str:numero>/", ticket_detail_view, name="ticket_detail"),
    path("meus-chamados/<str:numero>/mensagens/", ticket_message_create_view, name="ticket_message_create"),
    path("meus-chamados/<str:numero>/anexo/<int:anexo_id>/", download_anexo_view, name="download_anexo"),
    path("meus-chamados/<str:numero>/mensagens/anexo/<int:anexo_id>/", download_message_anexo_view, name="download_message_anexo"),
    path("contratos/", contratos_dashboard_view, name="contratos_dashboard"),
    path("contratos/requisicoes/criar/", requisicao_create_view, name="requisicao_create"),
    path("contratos/requisicoes/<int:requisicao_id>/", requisicao_detail_view, name="requisicao_detail"),
    path("contratos/requisicoes/<int:requisicao_id>/excluir/", requisicao_delete_view, name="requisicao_delete"),
    path("contratos/requisicoes/<int:requisicao_id>/marcar-entregue/", requisicao_marcar_entregue_view, name="requisicao_marcar_entregue"),
    path("contratos/requisicoes/<int:requisicao_id>/orcamentos/criar/", orcamento_create_view, name="orcamento_create"),
    path("contratos/orcamentos/<int:orcamento_id>/suborcamentos/criar/", suborcamento_create_view, name="suborcamento_create"),
    path("contratos/orcamentos/<int:orcamento_id>/aprovar/", orcamento_aprovar_view, name="orcamento_aprovar"),
    path("contratos/orcamentos/<int:orcamento_id>/foto/", contrato_orcamento_foto_view, name="contrato_orcamento_foto"),
    path("contratos/suborcamentos/<int:suborcamento_id>/foto/", contrato_suborcamento_foto_view, name="contrato_suborcamento_foto"),
    path("contratos/documentos/orcamento/<int:documento_id>/", contrato_orcamento_documento_view, name="contrato_orcamento_documento"),
    path("contratos/documentos/suborcamento/<int:documento_id>/", contrato_suborcamento_documento_view, name="contrato_suborcamento_documento"),
    path("emprestimos/", emprestimos_dashboard_view, name="emprestimos_dashboard"),
    path("emprestimos/criar/", emprestimo_create_view, name="emprestimo_create"),
    path("emprestimos/assinaturas/", assinaturas_list_view, name="assinaturas_list"),
    path("emprestimos/assinaturas/criar/", assinatura_create_view, name="assinatura_create"),
    path("emprestimos/<int:emprestimo_id>/", emprestimo_detail_view, name="emprestimo_detail"),
    path("emprestimos/<int:emprestimo_id>/baixar-termo/", emprestimo_baixar_termo_view, name="emprestimo_baixar_termo"),
    path("emprestimos/<int:emprestimo_id>/termo-assinado/", emprestimo_termo_assinado_view, name="emprestimo_termo_assinado"),
    path("emprestimos/fotos/<int:foto_id>/", emprestimo_foto_view, name="emprestimo_foto"),
    path("emprestimos/<int:emprestimo_id>/anexar-termo-assinado/", emprestimo_anexar_termo_assinado_view, name="emprestimo_anexar_termo_assinado"),
    path("emprestimos/<int:emprestimo_id>/marcar-documentacao-ok/", emprestimo_marcar_ok_view, name="emprestimo_marcar_ok"),
    path("documentos/", documentos_dashboard_view, name="documentos_dashboard"),
    path("documentos/criar/", documento_create_view, name="documento_create"),
    path("documentos/<int:documento_id>/", documento_detail_view, name="documento_detail"),
    path("documentos/anexos/<int:anexo_id>/", documento_anexo_download_view, name="documento_anexo_download"),
    path("insumos/", insumos_dashboard_view, name="insumos_dashboard"),
    path("insumos/criar/", insumo_create_view, name="insumo_create"),
    path("insumos/<int:insumo_id>/editar/", insumo_update_view, name="insumo_update"),
    path("insumos/<int:insumo_id>/entrada/", insumo_entrada_view, name="insumo_entrada"),
    path("insumos/<int:insumo_id>/excluir/", insumo_delete_view, name="insumo_delete"),
    path("insumos/<int:insumo_id>/retirar/", retirada_create_view, name="retirada_create"),
    path("insumos/retiradas/buscar/", retiradas_search_view, name="retiradas_search"),
    path("emails/", emails_dashboard_view, name="emails_dashboard"),
    path("emails/importar/", email_import_view, name="email_import"),
    path("emails/<int:conta_id>/", email_detail_view, name="email_detail"),
    path("ramais/", ramais_dashboard_view, name="ramais_dashboard"),
    path("ramais/criar/", ramal_create_view, name="ramal_create"),
    path("ramais/<int:ramal_id>/editar/", ramal_update_view, name="ramal_update"),
    path("ramais/<int:ramal_id>/excluir/", ramal_delete_view, name="ramal_delete"),
    path("licencas/", licencas_dashboard_view, name="licencas_dashboard"),
    path("licencas/softwares/criar/", licenca_software_create_view, name="licenca_software_create"),
    path("licencas/softwares/<int:software_id>/editar/", licenca_software_update_view, name="licenca_software_update"),
    path("licencas/softwares/<int:software_id>/excluir/", licenca_software_delete_view, name="licenca_software_delete"),
    path("licencas/criar/", licenca_create_view, name="licenca_create"),
    path("licencas/<int:licenca_id>/editar/", licenca_update_view, name="licenca_update"),
    path("licencas/<int:licenca_id>/excluir/", licenca_delete_view, name="licenca_delete"),
    path("ips/", ips_dashboard_view, name="ips_dashboard"),
    path("ips/criar/", ip_create_view, name="ip_create"),
    path("ips/<int:ip_id>/editar/", ip_update_view, name="ip_update"),
    path("ips/<int:ip_id>/excluir/", ip_delete_view, name="ip_delete"),
    path("servicos-feitos/", servicos_feitos_dashboard_view, name="servicos_feitos_dashboard"),
    path("servicos-feitos/criar/", servico_feito_create_view, name="servico_feito_create"),
    path("servicos-feitos/<int:servico_id>/", servico_feito_detail_view, name="servico_feito_detail"),
    path("servicos-feitos/<int:servico_id>/editar/", servico_feito_update_view, name="servico_feito_update"),
    path("servicos-feitos/<int:servico_id>/excluir/", servico_feito_delete_view, name="servico_feito_delete"),
    path("servicos-feitos/anexos/<int:anexo_id>/", servico_feito_anexo_download_view, name="servico_feito_anexo_download"),
    path("servicos-feitos/anexos/<int:anexo_id>/excluir/", servico_feito_anexo_delete_view, name="servico_feito_anexo_delete"),
    path("contratos-ti/", contratos_ti_dashboard_view, name="contratos_ti_dashboard"),
    path("contratos-ti/criar/", contrato_ti_create_view, name="contrato_ti_create"),
    path("contratos-ti/<int:contrato_id>/", contrato_ti_detail_view, name="contrato_ti_detail"),
    path("contratos-ti/<int:contrato_id>/editar/", contrato_ti_update_view, name="contrato_ti_update"),
    path("contratos-ti/<int:contrato_id>/excluir/", contrato_ti_delete_view, name="contrato_ti_delete"),
    path("contratos-ti/anexos/<int:anexo_id>/", contrato_ti_anexo_download_view, name="contrato_ti_anexo_download"),
    path("contratos-ti/anexos/<int:anexo_id>/excluir/", contrato_ti_anexo_delete_view, name="contrato_ti_anexo_delete"),
    path("futura-digital/", futura_digital_dashboard_view, name="futura_digital_dashboard"),
    path("futura-digital/criar/", futura_digital_create_view, name="futura_digital_create"),
    path("futura-digital/<int:fatura_id>/editar/", futura_digital_update_view, name="futura_digital_update"),
    path("futura-digital/<int:fatura_id>/excluir/", futura_digital_delete_view, name="futura_digital_delete"),
    path("futura-digital/<int:fatura_id>/documento/", futura_digital_documento_view, name="futura_digital_documento"),
    path("dicas/", dicas_dashboard_view, name="dicas_dashboard"),
    path("dicas/criar/", dica_create_view, name="dica_create"),
    path("dicas/<int:dica_id>/editar/", dica_update_view, name="dica_update"),
    path("dicas/<int:dica_id>/excluir/", dica_delete_view, name="dica_delete"),
    path("dicas/<int:dica_id>/anexo/", dica_anexo_view, name="dica_anexo"),
    path("starlinks/", starlinks_dashboard_view, name="starlinks_dashboard"),
    path("starlinks/criar/", starlink_create_view, name="starlink_create"),
    path("starlinks/<int:starlink_id>/editar/", starlink_update_view, name="starlink_update"),
    path("starlinks/<int:starlink_id>/excluir/", starlink_delete_view, name="starlink_delete"),
    path("cofre/", cofre_dashboard_view, name="cofre_dashboard"),
    path("cofre/senha-mestra/", cofre_set_master_view, name="cofre_set_master"),
    path("cofre/destravar/", cofre_unlock_view, name="cofre_unlock"),
    path("cofre/travar/", cofre_lock_view, name="cofre_lock"),
    path("cofre/credenciais/criar/", cofre_credencial_create_view, name="cofre_credencial_create"),
    path("cofre/credenciais/<int:credencial_id>/editar/", cofre_credencial_update_view, name="cofre_credencial_update"),
    path("cofre/credenciais/<int:credencial_id>/excluir/", cofre_credencial_delete_view, name="cofre_credencial_delete"),
    path("cofre/credenciais/<int:credencial_id>/revelar/", cofre_credencial_reveal_view, name="cofre_credencial_reveal"),
    path("email-config/", email_config_view, name="email_config"),
    path("email-config/salvar/", email_config_save_view, name="email_config_save"),
    path("email-config/testar/", email_config_test_view, name="email_config_test"),
    path("notificacoes/stream/", notificacoes_stream_view, name="notificacoes_stream"),
    path("historico/", history_view, name="history"),
    path("historico/buscar/", history_search_view, name="history_search"),
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path("permissoes/", permissions_view, name="permissions"),
    path("permissoes/<int:user_id>/toggle-atendente/", toggle_attendant_permission_view, name="toggle_attendant_permission"),
]
